# Generated by Django 5.1.2 on 2024-10-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='location',
            new_name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='accomodationDetails',
            field=models.TextField(default='Standard accommodation'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default='Within a week', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='guideDetails',
            field=models.TextField(default='A local guide will be assigned'),
        ),
        migrations.AddField(
            model_name='package',
            name='transferDetails',
            field=models.TextField(default='A Local transport will be arranged.Currently working on finding one.Will update you as soon as we find one'),
        ),
        migrations.CreateModel(
            name='FamousPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=1000)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.package')),
            ],
        ),
        migrations.CreateModel(
            name='Itenarary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1000)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.package')),
            ],
        ),
    ]
