# Generated by Django 5.1.2 on 2024-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_rename_location_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousplaces',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
